
services:
  _defaults:
    public: true

  # Module
  onlineshopmodule.module.legalcompliance.ps_legalcompliance:
    class: "PS_Legalcompliance"
    factory: ["Module", "getInstanceByName"]
    arguments:
      - 'ps_legalcompliance'

  # Controller
  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'

  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\LicenseAdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\LicenseAdminController
    parent: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    public: true

  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\ConfigurationAdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\ConfigurationAdminController
    parent: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    public: true

  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\CronAdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\CronAdminController
    parent: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    public: true

  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\LogAdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\LogAdminController
    parent: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    public: true

  Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\MaintenanceAdminController:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\MaintenanceAdminController
    parent: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Controller\AdminController
    public: true

  # License
  onlineshopmodule.module.legalcompliance.form.type.license:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\LicenseType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # Cron
  onlineshopmodule.module.legalcompliance.form.type.cron:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\CronType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  onlineshopmodule.module.legalcompliance.cronqueuerepository:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Cron\CronQueueRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $module: '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'

  onlineshopmodule.module.legalcompliance.cronpresenter:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Cron\CronPresenter
    arguments:
      $translator: '@translator'
      $module: '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      $legacyContext: '@prestashop.adapter.legacy.context'

  # Settings
  onlineshopmodule.module.legalcompliance.settings:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Settings
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  # Configuration
  onlineshopmodule.module.legalcompliance.configurationadapter:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Module\ConfigurationAdapter
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@prestashop.adapter.legacy.configuration'

  onlineshopmodule.module.legalcompliance.form.type.configuration:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\ConfigurationType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $context: '@=service("prestashop.adapter.legacy.context").getContext()'
    tags:
      - { name: form.type }

  onlineshopmodule.module.legalcompliance.form.type.payment:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\PaymentType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $context: '@=service("prestashop.adapter.legacy.context").getContext()'
      $module: '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
    tags:
      - { name: form.type }

  # Logs
  onlineshopmodule.module.legalcompliance.logrepository:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Log\LogRepository
    arguments:
      - '@filesystem'
      - 'ps_legalcompliance/'

  onlineshopmodule.module.legalcompliance.loglevel:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Log\LogLevel
    arguments:
      - '@onlineshopmodule.module.legalcompliance.configurationadapter'

  onlineshopmodule.module.legalcompliance.logger:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Log\Logger
    arguments:
      - '@onlineshopmodule.module.legalcompliance.logrepository'
      - '@onlineshopmodule.module.legalcompliance.loglevel'

  onlineshopmodule.module.legalcompliance.form.type.log:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\LogType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # Maintenance
  onlineshopmodule.module.legalcompliance.maintenance:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\Maintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.maintenance.hook'
      - '@onlineshopmodule.module.legalcompliance.maintenance.tab'
      - '@onlineshopmodule.module.legalcompliance.maintenance.sql'
      - '@onlineshopmodule.module.legalcompliance.maintenance.config'
      - '@onlineshopmodule.module.legalcompliance.maintenance.controller'
      - '@onlineshopmodule.module.legalcompliance.maintenance.orderstates'

  onlineshopmodule.module.legalcompliance.maintenance.hook:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\HookMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@=service("prestashop.adapter.shop.context").getContextShopID()'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  onlineshopmodule.module.legalcompliance.maintenance.tab:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\TabMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@prestashop.core.admin.tab.repository'
      - '@prestashop.adapter.module.tab.register'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getLanguages()'

  onlineshopmodule.module.legalcompliance.maintenance.sql:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\SqlMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  onlineshopmodule.module.legalcompliance.maintenance.config:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\ConfigMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@onlineshopmodule.module.legalcompliance.configurationadapter'

  onlineshopmodule.module.legalcompliance.maintenance.controller:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\ControllerMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  onlineshopmodule.module.legalcompliance.maintenance.orderstates:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Maintenance\OrderstateMaintenance
    arguments:
      - '@onlineshopmodule.module.legalcompliance.ps_legalcompliance'


# custom services here:

  pslegalcompliance.form_handler.label:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@pslegalcompliance.form_provider.label'
      - 'Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\LabelType'
      - 'PsLegalcomplianceLabel'
      - 'label'

  pslegalcompliance.form_handler.virtual:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@pslegalcompliance.form_provider.virtual'
      - 'Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\VirtualType'
      - 'PsLegalcomplianceVirtual'
      - 'virtual'

  pslegalcompliance.form_handler.general:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@pslegalcompliance.form_provider.general'
      - 'Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\GeneralType'
      - 'PsLegalcomplianceGeneral'
      - 'general'

  pslegalcompliance.form_handler.cms:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@pslegalcompliance.form_provider.cms'
      - 'Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\CmsType'
      - 'PsLegalcomplianceCms'
      - 'cms'

  pslegalcompliance.form_handler.email:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@pslegalcompliance.form_provider.email'
      - 'Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\EmailType'
      - 'PsLegalcomplianceEmail'
      - 'email'

  # Data Provider

  pslegalcompliance.entitymanager:
    class: PrestaShop\PrestaShop\Core\Foundation\Database\EntityManager
    arguments:
      - '@prestashop.adapter.database'
      - '@prestashop.adapter.legacy.configuration'

  pslegalcompliance.form_provider.label:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\DataProvider\LabelDataProvider
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"

  pslegalcompliance.form_provider.virtual:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\DataProvider\VirtualDataProvider
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"

  pslegalcompliance.form_provider.general:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\DataProvider\GeneralDataProvider
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - "@=service('prestashop.adapter.legacy.context').getAvailableLanguages()"

  pslegalcompliance.form_provider.cms:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\DataProvider\CmsDataProvider
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  pslegalcompliance.form_provider.email:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\DataProvider\EmailDataProvider
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@translator'
      - '@pslegalcompliance.entitymanager'

  # Form Types

  pslegalcompliance.form_type.label:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\LabelType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  pslegalcompliance.form_type.virtual:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\VirtualType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
    tags:
      - { name: form.type }

  pslegalcompliance.form_type.general:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\GeneralType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  pslegalcompliance.form_type.cms:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\CmsType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
    tags:
      - { name: form.type }

  pslegalcompliance.form_type.email:
    class: Onlineshopmodule\PrestaShop\Module\Legalcompliance\Form\Type\EmailType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
